"""Update table Asset, add file_path

Revision ID: 1cb875a077b2
Revises: b5f26928c528
Create Date: 2024-03-01 12:06:43.094961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb875a077b2'
down_revision: Union[str, None] = 'b5f26928c528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'file_path')
    # ### end Alembic commands ###
