"""Update table Asset, remove file_path

Revision ID: e431adf074c3
Revises: 1cb875a077b2
Create Date: 2024-03-25 09:38:11.507954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e431adf074c3'
down_revision: Union[str, None] = '1cb875a077b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
